version = 1

exclude_patterns = [
  "**/vendor/**",
  "tmp/**"
]

[[analyzers]]
name = "php"
enabled = true

[analyzers.meta]
  bootstrap_files = ["config/bootstrap.php"]

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true
